//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace IMSD.CusService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CustomerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerPurchaseAmountByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCustomerByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateCustomerInformationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerService() {
            this.Url = global::IMSD.Properties.Settings.Default.IMSD_CusService_CustomerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddCustomerCompletedEventHandler AddCustomerCompleted;
        
        /// <remarks/>
        public event GetAllCustomerCompletedEventHandler GetAllCustomerCompleted;
        
        /// <remarks/>
        public event GetCustomerPurchaseAmountByIdCompletedEventHandler GetCustomerPurchaseAmountByIdCompleted;
        
        /// <remarks/>
        public event GetCustomerListCompletedEventHandler GetCustomerListCompleted;
        
        /// <remarks/>
        public event DeleteCustomerByIdCompletedEventHandler DeleteCustomerByIdCompleted;
        
        /// <remarks/>
        public event GetCustomerByIdCompletedEventHandler GetCustomerByIdCompleted;
        
        /// <remarks/>
        public event updateCustomerInformationCompletedEventHandler updateCustomerInformationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddCustomer(string customerName, string customerAddress, string customerContact, string customerEmail, string customerStatus) {
            object[] results = this.Invoke("AddCustomer", new object[] {
                        customerName,
                        customerAddress,
                        customerContact,
                        customerEmail,
                        customerStatus});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddCustomerAsync(string customerName, string customerAddress, string customerContact, string customerEmail, string customerStatus) {
            this.AddCustomerAsync(customerName, customerAddress, customerContact, customerEmail, customerStatus, null);
        }
        
        /// <remarks/>
        public void AddCustomerAsync(string customerName, string customerAddress, string customerContact, string customerEmail, string customerStatus, object userState) {
            if ((this.AddCustomerOperationCompleted == null)) {
                this.AddCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCustomerOperationCompleted);
            }
            this.InvokeAsync("AddCustomer", new object[] {
                        customerName,
                        customerAddress,
                        customerContact,
                        customerEmail,
                        customerStatus}, this.AddCustomerOperationCompleted, userState);
        }
        
        private void OnAddCustomerOperationCompleted(object arg) {
            if ((this.AddCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCustomerCompleted(this, new AddCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllCustomer() {
            object[] results = this.Invoke("GetAllCustomer", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCustomerAsync() {
            this.GetAllCustomerAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCustomerAsync(object userState) {
            if ((this.GetAllCustomerOperationCompleted == null)) {
                this.GetAllCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCustomerOperationCompleted);
            }
            this.InvokeAsync("GetAllCustomer", new object[0], this.GetAllCustomerOperationCompleted, userState);
        }
        
        private void OnGetAllCustomerOperationCompleted(object arg) {
            if ((this.GetAllCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCustomerCompleted(this, new GetAllCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomerPurchaseAmountById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float GetCustomerPurchaseAmountById(string CusId) {
            object[] results = this.Invoke("GetCustomerPurchaseAmountById", new object[] {
                        CusId});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerPurchaseAmountByIdAsync(string CusId) {
            this.GetCustomerPurchaseAmountByIdAsync(CusId, null);
        }
        
        /// <remarks/>
        public void GetCustomerPurchaseAmountByIdAsync(string CusId, object userState) {
            if ((this.GetCustomerPurchaseAmountByIdOperationCompleted == null)) {
                this.GetCustomerPurchaseAmountByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerPurchaseAmountByIdOperationCompleted);
            }
            this.InvokeAsync("GetCustomerPurchaseAmountById", new object[] {
                        CusId}, this.GetCustomerPurchaseAmountByIdOperationCompleted, userState);
        }
        
        private void OnGetCustomerPurchaseAmountByIdOperationCompleted(object arg) {
            if ((this.GetCustomerPurchaseAmountByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerPurchaseAmountByIdCompleted(this, new GetCustomerPurchaseAmountByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomerList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCustomerList() {
            object[] results = this.Invoke("GetCustomerList", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerListAsync() {
            this.GetCustomerListAsync(null);
        }
        
        /// <remarks/>
        public void GetCustomerListAsync(object userState) {
            if ((this.GetCustomerListOperationCompleted == null)) {
                this.GetCustomerListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerListOperationCompleted);
            }
            this.InvokeAsync("GetCustomerList", new object[0], this.GetCustomerListOperationCompleted, userState);
        }
        
        private void OnGetCustomerListOperationCompleted(object arg) {
            if ((this.GetCustomerListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerListCompleted(this, new GetCustomerListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteCustomerById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteCustomerById(string id) {
            object[] results = this.Invoke("DeleteCustomerById", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCustomerByIdAsync(string id) {
            this.DeleteCustomerByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteCustomerByIdAsync(string id, object userState) {
            if ((this.DeleteCustomerByIdOperationCompleted == null)) {
                this.DeleteCustomerByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCustomerByIdOperationCompleted);
            }
            this.InvokeAsync("DeleteCustomerById", new object[] {
                        id}, this.DeleteCustomerByIdOperationCompleted, userState);
        }
        
        private void OnDeleteCustomerByIdOperationCompleted(object arg) {
            if ((this.DeleteCustomerByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCustomerByIdCompleted(this, new DeleteCustomerByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomerById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCustomerById(string id) {
            object[] results = this.Invoke("GetCustomerById", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerByIdAsync(string id) {
            this.GetCustomerByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetCustomerByIdAsync(string id, object userState) {
            if ((this.GetCustomerByIdOperationCompleted == null)) {
                this.GetCustomerByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerByIdOperationCompleted);
            }
            this.InvokeAsync("GetCustomerById", new object[] {
                        id}, this.GetCustomerByIdOperationCompleted, userState);
        }
        
        private void OnGetCustomerByIdOperationCompleted(object arg) {
            if ((this.GetCustomerByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerByIdCompleted(this, new GetCustomerByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateCustomerInformation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateCustomerInformation(string CId, string customerName, string CustomerAddress, string CustomerContact, string CustomerEmail, string scale) {
            object[] results = this.Invoke("updateCustomerInformation", new object[] {
                        CId,
                        customerName,
                        CustomerAddress,
                        CustomerContact,
                        CustomerEmail,
                        scale});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateCustomerInformationAsync(string CId, string customerName, string CustomerAddress, string CustomerContact, string CustomerEmail, string scale) {
            this.updateCustomerInformationAsync(CId, customerName, CustomerAddress, CustomerContact, CustomerEmail, scale, null);
        }
        
        /// <remarks/>
        public void updateCustomerInformationAsync(string CId, string customerName, string CustomerAddress, string CustomerContact, string CustomerEmail, string scale, object userState) {
            if ((this.updateCustomerInformationOperationCompleted == null)) {
                this.updateCustomerInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateCustomerInformationOperationCompleted);
            }
            this.InvokeAsync("updateCustomerInformation", new object[] {
                        CId,
                        customerName,
                        CustomerAddress,
                        CustomerContact,
                        CustomerEmail,
                        scale}, this.updateCustomerInformationOperationCompleted, userState);
        }
        
        private void OnupdateCustomerInformationOperationCompleted(object arg) {
            if ((this.updateCustomerInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCustomerInformationCompleted(this, new updateCustomerInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AddCustomerCompletedEventHandler(object sender, AddCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllCustomerCompletedEventHandler(object sender, GetAllCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetCustomerPurchaseAmountByIdCompletedEventHandler(object sender, GetCustomerPurchaseAmountByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerPurchaseAmountByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerPurchaseAmountByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetCustomerListCompletedEventHandler(object sender, GetCustomerListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DeleteCustomerByIdCompletedEventHandler(object sender, DeleteCustomerByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCustomerByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCustomerByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetCustomerByIdCompletedEventHandler(object sender, GetCustomerByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void updateCustomerInformationCompletedEventHandler(object sender, updateCustomerInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCustomerInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCustomerInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591