//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace IMSD.PurService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PurchaseServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PurchaseService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DoPurchaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProductQuantityByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCustomerPurchaseAmountByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPurchaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteSaleByIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PurchaseService() {
            this.Url = global::IMSD.Properties.Settings.Default.IMSD_PurService_PurchaseService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DoPurchaseCompletedEventHandler DoPurchaseCompleted;
        
        /// <remarks/>
        public event UpdateProductQuantityByIdCompletedEventHandler UpdateProductQuantityByIdCompleted;
        
        /// <remarks/>
        public event UpdateCustomerPurchaseAmountByIdCompletedEventHandler UpdateCustomerPurchaseAmountByIdCompleted;
        
        /// <remarks/>
        public event GetPurchaseCompletedEventHandler GetPurchaseCompleted;
        
        /// <remarks/>
        public event DeleteSaleByIdCompletedEventHandler DeleteSaleByIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DoPurchase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DoPurchase(string PId, int Quantity, string Scale, string Price, string CId) {
            object[] results = this.Invoke("DoPurchase", new object[] {
                        PId,
                        Quantity,
                        Scale,
                        Price,
                        CId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DoPurchaseAsync(string PId, int Quantity, string Scale, string Price, string CId) {
            this.DoPurchaseAsync(PId, Quantity, Scale, Price, CId, null);
        }
        
        /// <remarks/>
        public void DoPurchaseAsync(string PId, int Quantity, string Scale, string Price, string CId, object userState) {
            if ((this.DoPurchaseOperationCompleted == null)) {
                this.DoPurchaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoPurchaseOperationCompleted);
            }
            this.InvokeAsync("DoPurchase", new object[] {
                        PId,
                        Quantity,
                        Scale,
                        Price,
                        CId}, this.DoPurchaseOperationCompleted, userState);
        }
        
        private void OnDoPurchaseOperationCompleted(object arg) {
            if ((this.DoPurchaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoPurchaseCompleted(this, new DoPurchaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateProductQuantityById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateProductQuantityById(string PId, int Quantity) {
            object[] results = this.Invoke("UpdateProductQuantityById", new object[] {
                        PId,
                        Quantity});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateProductQuantityByIdAsync(string PId, int Quantity) {
            this.UpdateProductQuantityByIdAsync(PId, Quantity, null);
        }
        
        /// <remarks/>
        public void UpdateProductQuantityByIdAsync(string PId, int Quantity, object userState) {
            if ((this.UpdateProductQuantityByIdOperationCompleted == null)) {
                this.UpdateProductQuantityByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProductQuantityByIdOperationCompleted);
            }
            this.InvokeAsync("UpdateProductQuantityById", new object[] {
                        PId,
                        Quantity}, this.UpdateProductQuantityByIdOperationCompleted, userState);
        }
        
        private void OnUpdateProductQuantityByIdOperationCompleted(object arg) {
            if ((this.UpdateProductQuantityByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProductQuantityByIdCompleted(this, new UpdateProductQuantityByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCustomerPurchaseAmountById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateCustomerPurchaseAmountById(string CId, float Price) {
            object[] results = this.Invoke("UpdateCustomerPurchaseAmountById", new object[] {
                        CId,
                        Price});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCustomerPurchaseAmountByIdAsync(string CId, float Price) {
            this.UpdateCustomerPurchaseAmountByIdAsync(CId, Price, null);
        }
        
        /// <remarks/>
        public void UpdateCustomerPurchaseAmountByIdAsync(string CId, float Price, object userState) {
            if ((this.UpdateCustomerPurchaseAmountByIdOperationCompleted == null)) {
                this.UpdateCustomerPurchaseAmountByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCustomerPurchaseAmountByIdOperationCompleted);
            }
            this.InvokeAsync("UpdateCustomerPurchaseAmountById", new object[] {
                        CId,
                        Price}, this.UpdateCustomerPurchaseAmountByIdOperationCompleted, userState);
        }
        
        private void OnUpdateCustomerPurchaseAmountByIdOperationCompleted(object arg) {
            if ((this.UpdateCustomerPurchaseAmountByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCustomerPurchaseAmountByIdCompleted(this, new UpdateCustomerPurchaseAmountByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPurchase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetPurchase() {
            object[] results = this.Invoke("GetPurchase", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetPurchaseAsync() {
            this.GetPurchaseAsync(null);
        }
        
        /// <remarks/>
        public void GetPurchaseAsync(object userState) {
            if ((this.GetPurchaseOperationCompleted == null)) {
                this.GetPurchaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPurchaseOperationCompleted);
            }
            this.InvokeAsync("GetPurchase", new object[0], this.GetPurchaseOperationCompleted, userState);
        }
        
        private void OnGetPurchaseOperationCompleted(object arg) {
            if ((this.GetPurchaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPurchaseCompleted(this, new GetPurchaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteSaleById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteSaleById(string id) {
            object[] results = this.Invoke("DeleteSaleById", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteSaleByIdAsync(string id) {
            this.DeleteSaleByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteSaleByIdAsync(string id, object userState) {
            if ((this.DeleteSaleByIdOperationCompleted == null)) {
                this.DeleteSaleByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSaleByIdOperationCompleted);
            }
            this.InvokeAsync("DeleteSaleById", new object[] {
                        id}, this.DeleteSaleByIdOperationCompleted, userState);
        }
        
        private void OnDeleteSaleByIdOperationCompleted(object arg) {
            if ((this.DeleteSaleByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSaleByIdCompleted(this, new DeleteSaleByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DoPurchaseCompletedEventHandler(object sender, DoPurchaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoPurchaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoPurchaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdateProductQuantityByIdCompletedEventHandler(object sender, UpdateProductQuantityByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateProductQuantityByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateProductQuantityByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdateCustomerPurchaseAmountByIdCompletedEventHandler(object sender, UpdateCustomerPurchaseAmountByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCustomerPurchaseAmountByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCustomerPurchaseAmountByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetPurchaseCompletedEventHandler(object sender, GetPurchaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPurchaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPurchaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DeleteSaleByIdCompletedEventHandler(object sender, DeleteSaleByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteSaleByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteSaleByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591